// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/cubbies/[...cubby_hole].tsx";
import * as $1 from "./routes/api/cubbies/search.ts";
import * as $2 from "./routes/create.tsx";
import * as $3 from "./routes/cubbies/cubby/[...cubby_hole].tsx";
import * as $4 from "./routes/cubbies/delete/[...cubby_hole].ts";
import * as $5 from "./routes/cubbies/edit/[...cubby_hole].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/search.tsx";

const manifest = {
  routes: {
    "./routes/api/cubbies/[...cubby_hole].tsx": $0,
    "./routes/api/cubbies/search.ts": $1,
    "./routes/create.tsx": $2,
    "./routes/cubbies/cubby/[...cubby_hole].tsx": $3,
    "./routes/cubbies/delete/[...cubby_hole].ts": $4,
    "./routes/cubbies/edit/[...cubby_hole].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/search.tsx": $7,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
